export default {
  data() {
    return {
      modulePermis: [{
        'id': 1,
        'moduleName': '空间',
        'created': '2018-05-07 14:16:07',
        'status': 1,
        'permis': [{
          'id': 1,
          'permisName': '空间管理',
          'permisDesc': '',
          'status': 1,
          'permisModuleId': 1,
          'lvl': 1,
          'parentId': null,
          'created': '2018-05-07 14:21:02',
          'updated': '2018-05-07 14:21:04',
          'children': [{
            'id': 2,
            'permisName': '查看空间',
            'permisDesc': '',
            'status': 1,
            'permisModuleId': 1,
            'lvl': 2,
            'parentId': 1,
            'created': '2018-05-07 14:22:03',
            'updated': '2018-05-07 14:22:05',
            'children': [],
            'checked': false
          }, {
            'id': 3,
            'permisName': '添加空间',
            'permisDesc': '添加新的空间',
            'status': 1,
            'permisModuleId': 1,
            'lvl': 2,
            'parentId': 1,
            'created': '2018-05-07 14:22:38',
            'updated': '2018-05-07 14:22:42',
            'children': [],
            'checked': false
          }, {
            'id': 4,
            'permisName': '编辑空间',
            'permisDesc': '编辑空间信息/调整空间状态\r\n编辑空间信息/调整空间状态',
            'status': 1,
            'permisModuleId': 1,
            'lvl': 2,
            'parentId': 1,
            'created': '2018-05-07 14:23:17',
            'updated': '2018-05-07 14:23:20',
            'children': [],
            'checked': false
          }],
          'checked': false
        }],
        'allPermisIds': [1, 2, 3, 4],
        'checkedPermisIds': [],
        'checked': false
      }, {
        'id': 2,
        'moduleName': '场地',
        'created': '2018-05-07 14:16:34',
        'status': 1,
        'permis': [{
          'id': 5,
          'permisName': '场地管理',
          'permisDesc': null,
          'status': 1,
          'permisModuleId': 2,
          'lvl': 1,
          'parentId': null,
          'created': '2018-05-07 14:23:49',
          'updated': '2018-05-07 14:23:51',
          'children': [{
            'id': 6,
            'permisName': '查看场地',
            'permisDesc': '查看场地列表/场地日程/场地基本信息/对外开放信息',
            'status': 1,
            'permisModuleId': 2,
            'lvl': 2,
            'parentId': 5,
            'created': '2018-05-07 14:24:24',
            'updated': '2018-05-07 14:24:26',
            'children': [],
            'checked': false
          }, {
            'id': 7,
            'permisName': '添加场地',
            'permisDesc': '添加新的场地',
            'status': 1,
            'permisModuleId': 2,
            'lvl': 2,
            'parentId': 5,
            'created': '2018-05-07 14:24:56',
            'updated': '2018-05-07 14:24:58',
            'children': [],
            'checked': false
          }, {
            'id': 8,
            'permisName': '编辑场地',
            'permisDesc': '编辑、删除场地/场地日程/场地基本信息/对外开放信息',
            'status': 1,
            'permisModuleId': 2,
            'lvl': 2,
            'parentId': 5,
            'created': '2018-05-07 14:25:24',
            'updated': '2018-05-07 14:25:27',
            'children': [],
            'checked': false
          }, {
            'id': 9,
            'permisName': '预订场地',
            'permisDesc': '在系统操作场地预订',
            'status': 1,
            'permisModuleId': 2,
            'lvl': 2,
            'parentId': 5,
            'created': '2018-05-07 14:27:00',
            'updated': '2018-05-07 14:27:03',
            'children': [],
            'checked': false
          }],
          'checked': false
        }, {
          'id': 10,
          'permisName': '场地订单管理',
          'permisDesc': null,
          'status': 1,
          'permisModuleId': 2,
          'lvl': 1,
          'parentId': null,
          'created': '2018-05-07 14:27:46',
          'updated': '2018-05-07 14:27:49',
          'children': [{
            'id': 11,
            'permisName': '查看场地订单',
            'permisDesc': '查看订单列表/订单详情',
            'status': 1,
            'permisModuleId': 2,
            'lvl': 2,
            'parentId': 10,
            'created': '2018-05-07 14:35:40',
            'updated': '2018-05-07 14:35:43',
            'children': [],
            'checked': false
          }, {
            'id': 12,
            'permisName': '调整订单',
            'permisDesc': '确认收费/取消订单/调整订单金额',
            'status': 1,
            'permisModuleId': 2,
            'lvl': 2,
            'parentId': 10,
            'created': '2018-05-07 14:36:24',
            'updated': '2018-05-07 14:36:26',
            'children': [],
            'checked': false
          }, {
            'id': 13,
            'permisName': '导出',
            'permisDesc': '导出订单列表',
            'status': 1,
            'permisModuleId': 2,
            'lvl': 2,
            'parentId': 10,
            'created': '2018-05-07 14:37:10',
            'updated': '2018-05-07 14:37:12',
            'children': [],
            'checked': false
          }],
          'checked': false
        }],
        'allPermisIds': [5, 6, 7, 8, 9, 10, 11, 12, 13],
        'checkedPermisIds': [],
        'checked': false
      }, {
        'id': 3,
        'moduleName': '服务',
        'created': '2018-05-07 14:16:47',
        'status': 1,
        'permis': [{
          'id': 14,
          'permisName': '服务及服务商管理',
          'permisDesc': null,
          'status': 1,
          'permisModuleId': 3,
          'lvl': 1,
          'parentId': null,
          'created': '2018-05-07 14:38:54',
          'updated': '2018-05-07 14:38:57',
          'children': [{
            'id': 15,
            'permisName': '查看服务/服务商',
            'permisDesc': '查看服务/服务商的列表及详情',
            'status': 1,
            'permisModuleId': 3,
            'lvl': 2,
            'parentId': 14,
            'created': '2018-05-07 14:39:43',
            'updated': '2018-05-07 14:39:45',
            'children': [],
            'checked': false
          }, {
            'id': 16,
            'permisName': '添加服务/服务商',
            'permisDesc': '添加服务/服务商',
            'status': 1,
            'permisModuleId': 3,
            'lvl': 2,
            'parentId': 14,
            'created': '2018-05-07 14:40:21',
            'updated': '2018-05-07 14:40:23',
            'children': [],
            'checked': false
          }, {
            'id': 17,
            'permisName': '编辑服务/服务商',
            'permisDesc': '编辑服务/服务商',
            'status': 1,
            'permisModuleId': 3,
            'lvl': 2,
            'parentId': 14,
            'created': '2018-05-07 14:41:26',
            'updated': '2018-05-07 14:41:28',
            'children': [],
            'checked': false
          }],
          'checked': false
        }, {
          'id': 22,
          'permisName': '服务订单管理',
          'permisDesc': null,
          'status': 1,
          'permisModuleId': 3,
          'lvl': 1,
          'parentId': null,
          'created': '2018-05-07 14:49:49',
          'updated': '2018-05-07 14:49:52',
          'children': [{
            'id': 23,
            'permisName': '查看服务订单',
            'permisDesc': '查看订单列表/订单详情',
            'status': 1,
            'permisModuleId': 3,
            'lvl': 2,
            'parentId': 22,
            'created': '2018-05-07 14:50:30',
            'updated': '2018-05-07 14:50:33',
            'children': [],
            'checked': false
          }, {
            'id': 24,
            'permisName': '领取服务订单',
            'permisDesc': '领取用户提交的服务订单',
            'status': 1,
            'permisModuleId': 3,
            'lvl': 2,
            'parentId': 22,
            'created': '2018-05-07 14:51:05',
            'updated': '2018-05-07 14:51:08',
            'children': [],
            'checked': false
          }, {
            'id': 25,
            'permisName': '导出',
            'permisDesc': '导出订单列表',
            'status': 1,
            'permisModuleId': 3,
            'lvl': 2,
            'parentId': 22,
            'created': '2018-05-07 14:51:38',
            'updated': '2018-05-07 14:51:40',
            'children': [],
            'checked': false
          }],
          'checked': false
        }],
        'allPermisIds': [14, 15, 16, 17, 22, 23, 24, 25],
        'checkedPermisIds': [],
        'checked': false
      }, {
        'id': 4,
        'moduleName': '会员',
        'created': '2018-05-07 14:16:58',
        'status': 1,
        'permis': [{
          'id': 26,
          'permisName': '入驻企业管理',
          'permisDesc': null,
          'status': 1,
          'permisModuleId': 4,
          'lvl': 1,
          'parentId': null,
          'created': '2018-05-07 14:53:21',
          'updated': '2018-05-07 14:53:23',
          'children': [{
            'id': 27,
            'permisName': '添加企业',
            'permisDesc': '单个或批量添加企业',
            'status': 1,
            'permisModuleId': 4,
            'lvl': 2,
            'parentId': 26,
            'created': '2018-05-07 14:53:57',
            'updated': '2018-05-07 14:53:59',
            'children': [],
            'checked': false
          }, {
            'id': 28,
            'permisName': '查看企业',
            'permisDesc': '查看企业列表/企业详情',
            'status': 1,
            'permisModuleId': 4,
            'lvl': 2,
            'parentId': 26,
            'created': '2018-05-07 14:54:29',
            'updated': '2018-05-07 14:54:31',
            'children': [],
            'checked': false
          }, {
            'id': 29,
            'permisName': '编辑企业',
            'permisDesc': '编辑企业信息/编辑企业合同/调整企业状态',
            'status': 1,
            'permisModuleId': 4,
            'lvl': 2,
            'parentId': 26,
            'created': '2018-05-07 14:55:07',
            'updated': '2018-05-07 14:55:10',
            'children': [],
            'checked': false
          }, {
            'id': 30,
            'permisName': '导出',
            'permisDesc': '导出企业信息列表',
            'status': 1,
            'permisModuleId': 4,
            'lvl': 2,
            'parentId': 26,
            'created': '2018-05-07 14:55:36',
            'updated': '2018-05-07 14:55:38',
            'children': [],
            'checked': false
          }],
          'checked': false
        }, {
          'id': 31,
          'permisName': '会员列表',
          'permisDesc': null,
          'status': 1,
          'permisModuleId': 4,
          'lvl': 1,
          'parentId': null,
          'created': '2018-05-07 14:57:35',
          'updated': '2018-05-07 14:57:37',
          'children': [{
            'id': 32,
            'permisName': '查看会员',
            'permisDesc': '查看会员信息',
            'status': 1,
            'permisModuleId': 4,
            'lvl': 2,
            'parentId': 31,
            'created': '2018-05-07 14:58:06',
            'updated': '2018-05-07 14:58:08',
            'children': [],
            'checked': false
          }, {
            'id': 33,
            'permisName': '编辑会员',
            'permisDesc': '编辑会员备注名/备注/角色/可用状态',
            'status': 1,
            'permisModuleId': 4,
            'lvl': 2,
            'parentId': 31,
            'created': '2018-05-07 14:59:04',
            'updated': '2018-05-07 14:59:06',
            'children': [],
            'checked': false
          }, {
            'id': 34,
            'permisName': '导出',
            'permisDesc': '导出会员信息列表',
            'status': 1,
            'permisModuleId': 4,
            'lvl': 2,
            'parentId': 31,
            'created': '2018-05-07 14:59:41',
            'updated': '2018-05-07 14:59:43',
            'children': [],
            'checked': false
          }],
          'checked': false
        }, {
          'id': 35,
          'permisName': '会员营销管理',
          'permisDesc': null,
          'status': 1,
          'permisModuleId': 4,
          'lvl': 1,
          'parentId': null,
          'created': '2018-05-07 15:01:45',
          'updated': '2018-05-07 15:01:47',
          'children': [{
            'id': 36,
            'permisName': '查看积分',
            'permisDesc': '查看积分列表/积分详情',
            'status': 1,
            'permisModuleId': 4,
            'lvl': 2,
            'parentId': 35,
            'created': '2018-05-07 15:02:31',
            'updated': '2018-05-07 15:02:32',
            'children': [],
            'checked': false
          }, {
            'id': 37,
            'permisName': '添加积分规则',
            'permisDesc': '添加新的积分规则',
            'status': 1,
            'permisModuleId': 4,
            'lvl': 2,
            'parentId': 35,
            'created': '2018-05-07 15:03:01',
            'updated': '2018-05-07 15:03:03',
            'children': [],
            'checked': false
          }, {
            'id': 38,
            'permisName': '编辑积分规则',
            'permisDesc': '编辑、删除积分/编辑积分使用范围/调整积分规则状态',
            'status': 1,
            'permisModuleId': 4,
            'lvl': 2,
            'parentId': 35,
            'created': '2018-05-07 15:03:37',
            'updated': '2018-05-07 15:03:39',
            'children': [],
            'checked': false
          }, {
            'id': 39,
            'permisName': '积分充值',
            'permisDesc': '为会员充值积分',
            'status': 1,
            'permisModuleId': 4,
            'lvl': 2,
            'parentId': 35,
            'created': '2018-05-07 15:04:07',
            'updated': '2018-05-07 15:04:09',
            'children': [],
            'checked': false
          }, {
            'id': 40,
            'permisName': '查看优惠券',
            'permisDesc': '查看优惠券列表/优惠券详情',
            'status': 1,
            'permisModuleId': 4,
            'lvl': 2,
            'parentId': 35,
            'created': '2018-05-07 15:04:37',
            'updated': '2018-05-07 15:04:39',
            'children': [],
            'checked': false
          }, {
            'id': 41,
            'permisName': '添加优惠券',
            'permisDesc': '添加新的优惠券',
            'status': 1,
            'permisModuleId': 4,
            'lvl': 2,
            'parentId': 35,
            'created': '2018-05-07 16:56:33',
            'updated': '2018-05-07 16:56:35',
            'children': [],
            'checked': false
          }, {
            'id': 42,
            'permisName': '发放优惠券',
            'permisDesc': '发放优惠券至会员账户',
            'status': 1,
            'permisModuleId': 4,
            'lvl': 2,
            'parentId': 35,
            'created': '2018-05-07 15:05:03',
            'updated': '2018-05-07 15:05:05',
            'children': [],
            'checked': false
          }, {
            'id': 43,
            'permisName': '查看信用项',
            'permisDesc': '查看信用项列表',
            'status': 1,
            'permisModuleId': 4,
            'lvl': 2,
            'parentId': 35,
            'created': '2018-05-07 15:05:36',
            'updated': '2018-05-07 15:05:38',
            'children': [],
            'checked': false
          }, {
            'id': 44,
            'permisName': '添加评分规则项',
            'permisDesc': '添加新的评分规则项',
            'status': 1,
            'permisModuleId': 4,
            'lvl': 2,
            'parentId': 35,
            'created': '2018-05-07 15:06:06',
            'updated': '2018-05-07 15:06:09',
            'children': [],
            'checked': false
          }, {
            'id': 45,
            'permisName': '编辑信用体系',
            'permisDesc': '编辑信用体系说明/编辑、删除、停用评分项/编辑信用奖励',
            'status': 1,
            'permisModuleId': 4,
            'lvl': 2,
            'parentId': 35,
            'created': '2018-05-07 15:06:53',
            'updated': '2018-05-07 15:06:55',
            'children': [],
            'checked': false
          }, {
            'id': 46,
            'permisName': '登记信用',
            'permisDesc': '为会员登记信用评分项',
            'status': 1,
            'permisModuleId': 4,
            'lvl': 2,
            'parentId': 35,
            'created': '2018-05-07 15:07:22',
            'updated': '2018-05-07 15:07:24',
            'children': [],
            'checked': false
          }],
          'checked': false
        }],
        'allPermisIds': [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46],
        'checkedPermisIds': [],
        'checked': false
      }, {
        'id': 5,
        'moduleName': '工单',
        'created': '2018-05-07 14:17:15',
        'status': 1,
        'permis': [{
          'id': 47,
          'permisName': '参观预约管理',
          'permisDesc': null,
          'status': 1,
          'permisModuleId': 5,
          'lvl': 1,
          'parentId': null,
          'created': '2018-05-07 15:14:36',
          'updated': '2018-05-07 15:14:38',
          'children': [{
            'id': 48,
            'permisName': '查看参观预约',
            'permisDesc': null,
            'status': 1,
            'permisModuleId': 5,
            'lvl': 2,
            'parentId': 47,
            'created': '2018-05-07 15:15:15',
            'updated': '2018-05-07 15:15:16',
            'children': [],
            'checked': false
          }, {
            'id': 49,
            'permisName': '登记参观预约',
            'permisDesc': null,
            'status': 1,
            'permisModuleId': 5,
            'lvl': 2,
            'parentId': 47,
            'created': '2018-05-07 15:15:43',
            'updated': '2018-05-07 15:15:45',
            'children': [],
            'checked': false
          }, {
            'id': 50,
            'permisName': '导出',
            'permisDesc': null,
            'status': 1,
            'permisModuleId': 5,
            'lvl': 2,
            'parentId': 47,
            'created': '2018-05-07 15:16:09',
            'updated': '2018-05-07 15:16:11',
            'children': [],
            'checked': false
          }],
          'checked': false
        }, {
          'id': 51,
          'permisName': '故障报修管理',
          'permisDesc': null,
          'status': 1,
          'permisModuleId': 5,
          'lvl': 1,
          'parentId': null,
          'created': '2018-05-07 15:18:11',
          'updated': '2018-05-07 15:18:13',
          'children': [{
            'id': 52,
            'permisName': '查看故障报修',
            'permisDesc': null,
            'status': 1,
            'permisModuleId': 5,
            'lvl': 2,
            'parentId': 51,
            'created': '2018-05-07 15:18:41',
            'updated': '2018-05-07 15:18:43',
            'children': [],
            'checked': false
          }, {
            'id': 53,
            'permisName': '登记故障报修',
            'permisDesc': null,
            'status': 1,
            'permisModuleId': 5,
            'lvl': 2,
            'parentId': 51,
            'created': '2018-05-07 15:23:37',
            'updated': '2018-05-07 15:23:39',
            'children': [],
            'checked': false
          }, {
            'id': 54,
            'permisName': '导出',
            'permisDesc': null,
            'status': 1,
            'permisModuleId': 5,
            'lvl': 2,
            'parentId': 51,
            'created': '2018-05-07 15:23:57',
            'updated': '2018-05-07 15:23:59',
            'children': [],
            'checked': false
          }],
          'checked': false
        }, {
          'id': 55,
          'permisName': '入驻申请管理',
          'permisDesc': null,
          'status': 1,
          'permisModuleId': 5,
          'lvl': 1,
          'parentId': null,
          'created': '2018-05-07 15:24:23',
          'updated': '2018-05-07 15:24:26',
          'children': [{
            'id': 56,
            'permisName': '查看入驻申请',
            'permisDesc': null,
            'status': 1,
            'permisModuleId': 5,
            'lvl': 2,
            'parentId': 55,
            'created': '2018-05-07 15:24:56',
            'updated': '2018-05-07 15:24:58',
            'children': [],
            'checked': false
          }, {
            'id': 57,
            'permisName': '处理入驻申请',
            'permisDesc': null,
            'status': 1,
            'permisModuleId': 5,
            'lvl': 2,
            'parentId': 55,
            'created': '2018-05-07 15:25:28',
            'updated': '2018-05-07 15:25:30',
            'children': [],
            'checked': false
          }, {
            'id': 58,
            'permisName': '导出',
            'permisDesc': null,
            'status': 1,
            'permisModuleId': 5,
            'lvl': 2,
            'parentId': 55,
            'created': '2018-05-07 15:25:55',
            'updated': '2018-05-07 15:25:57',
            'children': [],
            'checked': false
          }],
          'checked': false
        }, {
          'id': 100,
          'permisName': '管家工单管理',
          'permisDesc': null,
          'status': 1,
          'permisModuleId': 5,
          'lvl': 1,
          'parentId': null,
          'created': '2018-05-09 10:22:09',
          'updated': '2018-05-09 10:22:11',
          'children': [{
            'id': 101,
            'permisName': '查看管家工单',
            'permisDesc': null,
            'status': 1,
            'permisModuleId': 5,
            'lvl': 2,
            'parentId': 100,
            'created': '2018-05-09 10:22:36',
            'updated': '2018-05-09 10:22:38',
            'children': [],
            'checked': false
          }, {
            'id': 102,
            'permisName': '处理管家工单',
            'permisDesc': null,
            'status': 1,
            'permisModuleId': 5,
            'lvl': 2,
            'parentId': 100,
            'created': '2018-05-09 10:23:17',
            'updated': '2018-05-09 10:23:20',
            'children': [],
            'checked': false
          }, {
            'id': 103,
            'permisName': '导出',
            'permisDesc': null,
            'status': 1,
            'permisModuleId': 5,
            'lvl': 2,
            'parentId': 100,
            'created': '2018-05-09 10:23:42',
            'updated': '2018-05-09 10:23:44',
            'children': [],
            'checked': false
          }],
          'checked': false
        }, {
          'id': 235,
          'permisName': '兑换记录',
          'permisDesc': null,
          'status': 1,
          'permisModuleId': 5,
          'lvl': 1,
          'parentId': null,
          'created': '2018-08-06 14:19:35',
          'updated': '2018-08-06 14:19:35',
          'children': [{
            'id': 236,
            'permisName': '查看兑换记录',
            'permisDesc': null,
            'status': 1,
            'permisModuleId': 5,
            'lvl': 2,
            'parentId': 235,
            'created': '2018-08-06 14:19:35',
            'updated': '2018-08-06 14:19:35',
            'children': [],
            'checked': false
          }],
          'checked': false
        }],
        'allPermisIds': [47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 100, 101, 102, 103, 235, 236],
        'checkedPermisIds': [],
        'checked': false
      }, {
        'id': 6,
        'moduleName': '财务',
        'created': '2018-05-07 14:17:39',
        'status': 1,
        'permis': [{
          'id': 59,
          'permisName': '退款审批',
          'permisDesc': null,
          'status': 1,
          'permisModuleId': 6,
          'lvl': 1,
          'parentId': null,
          'created': '2018-05-07 15:26:37',
          'updated': '2018-05-07 15:26:39',
          'children': [{
            'id': 60,
            'permisName': '查看退款申请',
            'permisDesc': '查看退款申请列表/详情',
            'status': 1,
            'permisModuleId': 6,
            'lvl': 2,
            'parentId': 59,
            'created': '2018-05-07 15:27:11',
            'updated': '2018-05-07 15:27:13',
            'children': [],
            'checked': false
          }, {
            'id': 61,
            'permisName': '审批退款申请',
            'permisDesc': '审批取消订单的退款申请',
            'status': 1,
            'permisModuleId': 6,
            'lvl': 2,
            'parentId': 59,
            'created': '2018-05-07 15:27:46',
            'updated': '2018-05-07 15:27:49',
            'children': [],
            'checked': false
          }],
          'checked': false
        }, {
          'id': 62,
          'permisName': '结算单',
          'permisDesc': null,
          'status': 1,
          'permisModuleId': 6,
          'lvl': 1,
          'parentId': null,
          'created': '2018-05-07 17:28:17',
          'updated': '2018-05-07 17:28:19',
          'children': [{
            'id': 63,
            'permisName': '查看月度结算单',
            'permisDesc': '查看企业的月度结算账单',
            'status': 1,
            'permisModuleId': 6,
            'lvl': 2,
            'parentId': 62,
            'created': '2018-05-07 15:28:34',
            'updated': '2018-05-07 15:28:38',
            'children': [],
            'checked': false
          }, {
            'id': 64,
            'permisName': '导出结算单汇总',
            'permisDesc': '导出结算单汇总表格',
            'status': 1,
            'permisModuleId': 6,
            'lvl': 2,
            'parentId': 62,
            'created': '2018-05-07 15:29:06',
            'updated': '2018-05-07 15:29:08',
            'children': [],
            'checked': false
          }, {
            'id': 65,
            'permisName': '导出结算单清单',
            'permisDesc': '导出结算单的明细',
            'status': 1,
            'permisModuleId': 6,
            'lvl': 2,
            'parentId': 62,
            'created': '2018-05-07 15:29:41',
            'updated': '2018-05-07 15:29:43',
            'children': [],
            'checked': false
          }, {
            'id': 66,
            'permisName': '收取结算单费用',
            'permisDesc': '线下收取并登记结算单费用',
            'status': 1,
            'permisModuleId': 6,
            'lvl': 2,
            'parentId': 62,
            'created': '2018-05-07 15:30:18',
            'updated': '2018-05-07 15:30:20',
            'children': [],
            'checked': false
          }, {
            'id': 234,
            'permisName': '调整结算单费用',
            'permisDesc': null,
            'status': 1,
            'permisModuleId': 6,
            'lvl': 2,
            'parentId': 62,
            'created': '2018-05-09 17:42:08',
            'updated': '2018-05-09 17:42:08',
            'children': [],
            'checked': false
          }],
          'checked': false
        }],
        'allPermisIds': [59, 60, 61, 62, 63, 64, 65, 66, 234],
        'checkedPermisIds': [],
        'checked': false
      }, {
        'id': 7,
        'moduleName': '统计',
        'created': '2018-05-07 14:17:58',
        'status': 1,
        'permis': [{
          'id': 67,
          'permisName': '运营数据',
          'permisDesc': null,
          'status': 1,
          'permisModuleId': 7,
          'lvl': 1,
          'parentId': null,
          'created': '2018-05-07 15:31:06',
          'updated': '2018-05-07 15:31:08',
          'children': [{
            'id': 68,
            'permisName': '查看运营数据',
            'permisDesc': '查看运营数据统计',
            'status': 1,
            'permisModuleId': 7,
            'lvl': 2,
            'parentId': 67,
            'created': '2018-05-07 15:31:39',
            'updated': '2018-05-07 15:31:41',
            'children': [],
            'checked': false
          }, {
            'id': 69,
            'permisName': '导出',
            'permisDesc': '导出运营数据',
            'status': 1,
            'permisModuleId': 7,
            'lvl': 2,
            'parentId': 67,
            'created': '2018-05-07 15:32:17',
            'updated': '2018-05-07 15:32:19',
            'children': [],
            'checked': false
          }],
          'checked': false
        }],
        'allPermisIds': [67, 68, 69],
        'checkedPermisIds': [],
        'checked': false
      }, {
        'id': 8,
        'moduleName': '资产',
        'created': '2018-05-07 14:18:12',
        'status': 1,
        'permis': [{
          'id': 70,
          'permisName': '资产管理',
          'permisDesc': null,
          'status': 1,
          'permisModuleId': 8,
          'lvl': 1,
          'parentId': null,
          'created': '2018-05-07 15:33:10',
          'updated': '2018-05-07 15:33:12',
          'children': [{
            'id': 71,
            'permisName': '查看固资',
            'permisDesc': '查看固定资产列表',
            'status': 1,
            'permisModuleId': 8,
            'lvl': 2,
            'parentId': 70,
            'created': '2018-05-07 15:33:50',
            'updated': '2018-05-07 15:33:52',
            'children': [],
            'checked': false
          }, {
            'id': 72,
            'permisName': '管理固资',
            'permisDesc': '创建/编辑/删除 固定资产',
            'status': 1,
            'permisModuleId': 8,
            'lvl': 2,
            'parentId': 70,
            'created': '2018-05-07 15:34:21',
            'updated': '2018-05-07 15:34:23',
            'children': [],
            'checked': false
          }, {
            'id': 73,
            'permisName': '添加固资',
            'permisDesc': '添加新的固定资产',
            'status': 1,
            'permisModuleId': 8,
            'lvl': 2,
            'parentId': 70,
            'created': '2018-05-07 15:35:03',
            'updated': '2018-05-07 15:35:05',
            'children': [],
            'checked': false
          }, {
            'id': 74,
            'permisName': '登记固资',
            'permisDesc': '为企业登记固资借还情况',
            'status': 1,
            'permisModuleId': 8,
            'lvl': 2,
            'parentId': 70,
            'created': '2018-05-07 15:35:41',
            'updated': '2018-05-07 15:35:44',
            'children': [],
            'checked': false
          }],
          'checked': false
        }],
        'allPermisIds': [70, 71, 72, 73, 74],
        'checkedPermisIds': [],
        'checked': false
      }, {
        'id': 9,
        'moduleName': '空间设置',
        'created': '2018-05-07 14:18:27',
        'status': 1,
        'permis': [{
          'id': 75,
          'permisName': '空间设置管理',
          'permisDesc': null,
          'status': 1,
          'permisModuleId': 9,
          'lvl': 1,
          'parentId': null,
          'created': '2018-05-07 15:36:22',
          'updated': '2018-05-07 15:36:23',
          'children': [{
            'id': 76,
            'permisName': '编辑空间信息',
            'permisDesc': null,
            'status': 1,
            'permisModuleId': 9,
            'lvl': 2,
            'parentId': 75,
            'created': '2018-05-07 15:37:07',
            'updated': '2018-05-07 15:37:09',
            'children': [],
            'checked': false
          }],
          'checked': false
        }],
        'allPermisIds': [75, 76],
        'checkedPermisIds': [],
        'checked': false
      }, {
        'id': 10,
        'moduleName': '智能硬件',
        'created': '2018-05-07 14:18:40',
        'status': 1,
        'permis': [{
          'id': 77,
          'permisName': '智能硬件管理',
          'permisDesc': null,
          'status': 1,
          'permisModuleId': 10,
          'lvl': 1,
          'parentId': null,
          'created': '2018-05-07 15:37:46',
          'updated': '2018-05-07 15:37:49',
          'children': [{
            'id': 78,
            'permisName': '查看门禁',
            'permisDesc': '查看门禁列表/门禁详情',
            'status': 1,
            'permisModuleId': 10,
            'lvl': 2,
            'parentId': 77,
            'created': '2018-05-07 15:38:56',
            'updated': '2018-05-07 15:38:59',
            'children': [],
            'checked': false
          }, {
            'id': 79,
            'permisName': '添加门禁',
            'permisDesc': null,
            'status': 1,
            'permisModuleId': 10,
            'lvl': 2,
            'parentId': 77,
            'created': '2018-05-07 15:39:51',
            'updated': '2018-05-07 15:39:53',
            'children': [],
            'checked': false
          }],
          'checked': false
        }],
        'allPermisIds': [77, 78, 79],
        'checkedPermisIds': [],
        'checked': false
      }, {
        'id': 11,
        'moduleName': '账户权限',
        'created': '2018-05-07 14:19:09',
        'status': 1,
        'permis': [{
          'id': 80,
          'permisName': '空间管家',
          'permisDesc': null,
          'status': 1,
          'permisModuleId': 11,
          'lvl': 1,
          'parentId': null,
          'created': '2018-05-07 15:40:26',
          'updated': '2018-05-07 15:40:28',
          'children': [{
            'id': 81,
            'permisName': '查看空间管家',
            'permisDesc': null,
            'status': 1,
            'permisModuleId': 11,
            'lvl': 2,
            'parentId': 80,
            'created': '2018-05-07 15:42:34',
            'updated': '2018-05-07 15:42:36',
            'children': [],
            'checked': false
          }, {
            'id': 82,
            'permisName': '添加空间管家',
            'permisDesc': '编辑服务类型',
            'status': 1,
            'permisModuleId': 11,
            'lvl': 2,
            'parentId': 80,
            'created': '2018-05-07 15:43:19',
            'updated': '2018-05-07 15:43:21',
            'children': [],
            'checked': false
          }, {
            'id': 83,
            'permisName': '编辑管家设置',
            'permisDesc': '编辑服务类型',
            'status': 1,
            'permisModuleId': 11,
            'lvl': 2,
            'parentId': 80,
            'created': '2018-05-07 15:43:56',
            'updated': '2018-05-07 15:43:58',
            'children': [],
            'checked': false
          }, {
            'id': 233,
            'permisName': '编辑管家',
            'permisDesc': '管理管家负责企业',
            'status': 1,
            'permisModuleId': 11,
            'lvl': 2,
            'parentId': 80,
            'created': '2018-05-09 12:27:15',
            'updated': '2018-05-09 12:27:15',
            'children': [],
            'checked': false
          }],
          'checked': false
        }, {
          'id': 237,
          'permisName': '员工列表',
          'permisDesc': null,
          'status': 1,
          'permisModuleId': 11,
          'lvl': 1,
          'parentId': null,
          'created': '2018-10-08 17:30:08',
          'updated': '2018-10-08 17:30:08',
          'children': [{
            'id': 238,
            'permisName': '查看管理员账户',
            'permisDesc': null,
            'status': 1,
            'permisModuleId': 11,
            'lvl': 2,
            'parentId': 237,
            'created': '2018-10-08 17:35:38',
            'updated': '2018-10-08 17:35:38',
            'children': [],
            'checked': false
          }, {
            'id': 239,
            'permisName': '添加账户',
            'permisDesc': '添加新的账户',
            'status': 1,
            'permisModuleId': 11,
            'lvl': 2,
            'parentId': 237,
            'created': '2018-10-08 17:36:02',
            'updated': '2018-10-08 17:36:02',
            'children': [],
            'checked': false
          }, {
            'id': 240,
            'permisName': '编辑账户',
            'permisDesc': '编辑账户信息/删除账户/调整账户状态',
            'status': 1,
            'permisModuleId': 11,
            'lvl': 2,
            'parentId': 237,
            'created': '2018-10-08 17:36:29',
            'updated': '2018-10-08 17:36:29',
            'children': [],
            'checked': false
          }, {
            'id': 241,
            'permisName': '查看职务列表',
            'permisDesc': null,
            'status': 1,
            'permisModuleId': 11,
            'lvl': 2,
            'parentId': 237,
            'created': '2018-10-08 17:36:53',
            'updated': '2018-10-08 17:36:53',
            'children': [],
            'checked': false
          }, {
            'id': 242,
            'permisName': '添加职务',
            'permisDesc': '添加新的职务',
            'status': 1,
            'permisModuleId': 11,
            'lvl': 2,
            'parentId': 237,
            'created': '2018-10-08 17:37:12',
            'updated': '2018-10-08 17:37:12',
            'children': [],
            'checked': false
          }, {
            'id': 243,
            'permisName': '编辑职务',
            'permisDesc': '编辑职务信息/删除职务/调整职务状态',
            'status': 1,
            'permisModuleId': 11,
            'lvl': 2,
            'parentId': 237,
            'created': '2018-10-08 17:37:36',
            'updated': '2018-10-08 17:37:36',
            'children': [],
            'checked': false
          }, {
            'id': 244,
            'permisName': '管理人员',
            'permisDesc': null,
            'status': 1,
            'permisModuleId': 11,
            'lvl': 2,
            'parentId': 237,
            'created': '2018-10-15 11:55:44',
            'updated': '2018-10-15 11:55:44',
            'children': [],
            'checked': false
          }],
          'checked': false
        }],
        'allPermisIds': [80, 81, 82, 83, 233, 237, 238, 239, 240, 241, 242, 243, 244],
        'checkedPermisIds': [],
        'checked': false
      }, {
        'id': 12,
        'moduleName': '系统设置',
        'created': '2018-05-07 15:08:59',
        'status': 1,
        'permis': [{
          'id': 84,
          'permisName': '系统设置',
          'permisDesc': null,
          'status': 1,
          'permisModuleId': 12,
          'lvl': 1,
          'parentId': null,
          'created': '2018-05-07 15:44:28',
          'updated': '2018-05-07 15:44:30',
          'children': [{
            'id': 85,
            'permisName': '多媒体管理',
            'permisDesc': null,
            'status': 1,
            'permisModuleId': 12,
            'lvl': 2,
            'parentId': 84,
            'created': '2018-05-07 15:44:57',
            'updated': '2018-05-07 15:44:58',
            'children': [],
            'checked': false
          }, {
            'id': 86,
            'permisName': '平板端管理',
            'permisDesc': null,
            'status': 1,
            'permisModuleId': 12,
            'lvl': 2,
            'parentId': 84,
            'created': '2018-05-07 15:45:24',
            'updated': '2018-05-07 15:45:26',
            'children': [],
            'checked': false
          }, {
            'id': 87,
            'permisName': '查看操作日志',
            'permisDesc': null,
            'status': 1,
            'permisModuleId': 12,
            'lvl': 2,
            'parentId': 84,
            'created': '2018-05-07 15:45:45',
            'updated': '2018-05-07 15:45:47',
            'children': [],
            'checked': false
          }, {
            'id': 88,
            'permisName': '导出操作日志',
            'permisDesc': null,
            'status': 1,
            'permisModuleId': 12,
            'lvl': 2,
            'parentId': 84,
            'created': '2018-05-07 15:46:12',
            'updated': '2018-05-07 15:46:14',
            'children': [],
            'checked': false
          }, {
            'id': 89,
            'permisName': '参数配置',
            'permisDesc': null,
            'status': 1,
            'permisModuleId': 12,
            'lvl': 2,
            'parentId': 84,
            'created': '2018-05-07 15:46:35',
            'updated': '2018-05-07 15:46:37',
            'children': [],
            'checked': false
          }],
          'checked': false
        }],
        'allPermisIds': [84, 85, 86, 87, 88, 89],
        'checkedPermisIds': [],
        'checked': false
      }, {
        'id': 13,
        'moduleName': '门店公告',
        'created': '2018-05-08 17:43:16',
        'status': 1,
        'permis': [{
          'id': 90,
          'permisName': '空间公告管理',
          'permisDesc': null,
          'status': 1,
          'permisModuleId': 13,
          'lvl': 1,
          'parentId': null,
          'created': '2018-05-08 17:55:15',
          'updated': '2018-05-08 17:55:17',
          'children': [{
            'id': 91,
            'permisName': '查看空间公告',
            'permisDesc': null,
            'status': 1,
            'permisModuleId': 13,
            'lvl': 2,
            'parentId': 90,
            'created': '2018-05-08 17:56:03',
            'updated': '2018-05-08 17:56:06',
            'children': [],
            'checked': false
          }, {
            'id': 92,
            'permisName': '添加/编辑空间公告',
            'permisDesc': null,
            'status': 1,
            'permisModuleId': 13,
            'lvl': 2,
            'parentId': 90,
            'created': '2018-05-08 17:56:43',
            'updated': '2018-05-08 17:56:46',
            'children': [],
            'checked': false
          }],
          'checked': false
        }],
        'allPermisIds': [90, 91, 92],
        'checkedPermisIds': [],
        'checked': false
      }, {
        'id': 14,
        'moduleName': '活动公告',
        'created': '2018-05-08 17:43:31',
        'status': 1,
        'permis': [{
          'id': 95,
          'permisName': '活动公告管理',
          'permisDesc': null,
          'status': 1,
          'permisModuleId': 14,
          'lvl': 1,
          'parentId': null,
          'created': '2018-05-08 17:58:21',
          'updated': '2018-05-08 17:58:23',
          'children': [{
            'id': 96,
            'permisName': '查看活动公告',
            'permisDesc': null,
            'status': 1,
            'permisModuleId': 14,
            'lvl': 2,
            'parentId': 95,
            'created': '2018-05-08 17:58:59',
            'updated': '2018-05-08 17:59:01',
            'children': [],
            'checked': false
          }, {
            'id': 97,
            'permisName': '添加活动公告',
            'permisDesc': null,
            'status': 1,
            'permisModuleId': 14,
            'lvl': 2,
            'parentId': 95,
            'created': '2018-05-08 17:59:26',
            'updated': '2018-05-08 17:59:28',
            'children': [],
            'checked': false
          }, {
            'id': 98,
            'permisName': '编辑活动公告',
            'permisDesc': null,
            'status': 1,
            'permisModuleId': 14,
            'lvl': 2,
            'parentId': 95,
            'created': '2018-05-08 18:04:56',
            'updated': '2018-05-08 18:04:58',
            'children': [],
            'checked': false
          }],
          'checked': false
        }],
        'allPermisIds': [95, 96, 97, 98],
        'checkedPermisIds': [],
        'checked': false
      }]
    }
  }
}
